theme: jekyll-theme-time-machine
sass:
    sass_dir: _sass

assets:
  digest: true
  compress:
    css:  true
  prefix: "/assets"
  sources:
    - _assets/
    - _assets/js
    - _assets/css
    - _assets/javascript
    - _assets/stylesheets
    - _assets/img
    - _assets/fonts
